# Generated by Django 4.1.1 on 2022-11-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lcl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=15)),
                ('dest', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('cur', models.CharField(max_length=15)),
                ('rate', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=15)),
                ('chargeAt', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=15)),
            ],
        ),
    ]
