# Generated by Django 4.1.1 on 2022-11-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simfulloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=15)),
                ('dest', models.CharField(max_length=15)),
                ('consol', models.CharField(max_length=15)),
                ('line', models.CharField(max_length=15)),
                ('cur_min', models.CharField(max_length=15)),
                ('minimum', models.CharField(max_length=15)),
                ('cur_nor', models.CharField(max_length=15)),
                ('normal', models.CharField(max_length=15)),
                ('cur_45', models.CharField(max_length=15)),
                ('over45', models.CharField(max_length=15)),
                ('cur_100', models.CharField(max_length=15)),
                ('over100', models.CharField(max_length=15)),
                ('cur_300', models.CharField(max_length=15)),
                ('over300', models.CharField(max_length=15)),
                ('cur_500', models.CharField(max_length=15)),
                ('over500', models.CharField(max_length=15)),
                ('cur_1000', models.CharField(max_length=15)),
                ('over1000', models.CharField(max_length=15)),
            ],
        ),
    ]
