# Generated by Django 4.1.1 on 2022-11-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simfulloapp', '0003_rename_cur_100_air_cur_rename_cur_1000_air_fsc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='airother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=15)),
                ('dest', models.CharField(max_length=15)),
                ('consol', models.CharField(max_length=15)),
                ('line', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('cur', models.CharField(max_length=15)),
                ('rate', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=15)),
                ('chargeaAt', models.CharField(max_length=15)),
            ],
        ),
    ]
