# Generated by Django 4.1.1 on 2022-11-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simfulloapp', '0004_airother'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airother',
            old_name='chargeaAt',
            new_name='airother_chargeaAt',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='consol',
            new_name='airother_consol',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='cur',
            new_name='airother_cur',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='dest',
            new_name='airother_dest',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='line',
            new_name='airother_line',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='name',
            new_name='airother_name',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='origin',
            new_name='airother_origin',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='rate',
            new_name='airother_rate',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='unit',
            new_name='airother_unit',
        ),
    ]
