# Generated by Django 4.0.5 on 2022-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simfulloapp', '0006_rename_airother_chargeaat_airother_airother_chargeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=15)),
                ('dest', models.CharField(max_length=15)),
                ('line', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('cur', models.CharField(max_length=15)),
                ('rate', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=15)),
                ('chargeAt', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_chargeAt',
            new_name='chargeAt',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_consol',
            new_name='cur',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_cur',
            new_name='dest',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_dest',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_line',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_name',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_origin',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='airother',
            old_name='airother_rate',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='airother',
            name='airother_unit',
        ),
    ]
