# Generated by Django 4.0.5 on 2022-12-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simfulloapp', '0007_fcl_rename_airother_chargeat_airother_chargeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcl',
            name='ttime',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcl',
            name='validity',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
