# Generated by Django 4.1.1 on 2022-12-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_nickname_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
